#!/usr/bin/env bash

set -u

ROOT="$(git rev-parse --show-toplevel)"
cd "$ROOT"

ENV_FILE="$ROOT/.env"
STATE_DIR="$ROOT/.autonavlog-worktree"
MARKER="# Generated by AutoNavLog Codex worktree setup"

if [[ ! -f "$ENV_FILE" ]]; then
    exit 0
fi

if ! grep -qxF "$MARKER" "$ENV_FILE"; then
    echo "Refusing cleanup because .env was not generated by the Codex worktree setup." >&2
    exit 1
fi

set -a
# shellcheck disable=SC1090
source "$ENV_FILE"
set +a

if [[ ! "${COMPOSE_PROJECT_NAME:-}" =~ ^autonavlog-wt-[0-9a-f]{8}$ ]]; then
    echo "Refusing volume cleanup for unexpected project: ${COMPOSE_PROJECT_NAME:-<unset>}" >&2
    exit 1
fi
if [[ ! "${AUTONAVLOG_IMAGE:-}" =~ ^autonavlog:wt-[0-9a-f]{8}$ ]]; then
    echo "Refusing image cleanup for unexpected image: ${AUTONAVLOG_IMAGE:-<unset>}" >&2
    exit 1
fi

if command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1; then
    if ! docker compose down -v --remove-orphans; then
        echo "Warning: generated Compose configuration failed; retrying cleanup with the base Compose file." >&2
        COMPOSE_FILE=compose.yaml docker compose -p "$COMPOSE_PROJECT_NAME" down -v --remove-orphans || true
    fi
    docker image rm "$AUTONAVLOG_IMAGE" >/dev/null 2>&1 || true
else
    echo "Warning: Docker is unavailable; worktree Docker resources were not removed." >&2
fi

rm -rf "$STATE_DIR"
rm -f "$ENV_FILE"
