#!/usr/bin/env bash

set -euo pipefail

ROOT="$(git rev-parse --show-toplevel)"
cd "$ROOT"

for command_name in docker python3 node npm; do
    if ! command -v "$command_name" >/dev/null 2>&1; then
        echo "Required command not found: $command_name" >&2
        exit 1
    fi
done

docker compose version >/dev/null

ENV_FILE="$ROOT/.env"
STATE_DIR="$ROOT/.autonavlog-worktree"
OVERRIDE_FILE="$STATE_DIR/compose.override.yaml"
MARKER="# Generated by AutoNavLog Codex worktree setup"

write_override() {
    mkdir -p "$STATE_DIR"

    if [[ "$COMPOSE_FILE" == *"compose.wsl.yaml"* ]]; then
        cat >"$OVERRIDE_FILE" <<EOF
services:
  autonavlog:
    image: "${AUTONAVLOG_IMAGE}"
    command:
      - --host
      - 0.0.0.0
      - --port
      - "${AUTONAVLOG_HOST_PORT}"
      - --data-root
      - /opt/autonavlog/data
      - --storage-root
      - /var/lib/autonavlog
      - --weather
      - msm
      - --maximum-sessions
      - "256"
    healthcheck:
      test:
        - CMD
        - python
        - -c
        - "import urllib.request; urllib.request.urlopen('http://127.0.0.1:${AUTONAVLOG_HOST_PORT}/healthz', timeout=3).read()"
EOF
    else
        cat >"$OVERRIDE_FILE" <<EOF
services:
  autonavlog:
    image: "${AUTONAVLOG_IMAGE}"
EOF
    fi
}

if [[ -e "$ENV_FILE" ]]; then
    if ! grep -qxF "$MARKER" "$ENV_FILE"; then
        echo "Refusing to overwrite existing .env; move it or configure this worktree manually." >&2
        exit 1
    fi

    set -a
    # shellcheck disable=SC1090
    source "$ENV_FILE"
    set +a

    : "${COMPOSE_PROJECT_NAME:?Generated .env is missing COMPOSE_PROJECT_NAME}"
    : "${COMPOSE_FILE:?Generated .env is missing COMPOSE_FILE}"
    : "${AUTONAVLOG_IMAGE:?Generated .env is missing AUTONAVLOG_IMAGE}"
    : "${AUTONAVLOG_HOST_PORT:?Generated .env is missing AUTONAVLOG_HOST_PORT}"
else
    read -r WT_ID WT_PORT < <(
        python3 - "$ROOT" <<'PY'
import hashlib
import socket
import sys

root = sys.argv[1]
digest = hashlib.sha256(root.encode()).hexdigest()
worktree_id = digest[:8]
first_port = 20000 + int(digest[8:16], 16) % 40000

for offset in range(40000):
    port = 20000 + ((first_port - 20000 + offset) % 40000)
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        try:
            sock.bind(("0.0.0.0", port))
        except OSError:
            continue
    print(worktree_id, port)
    break
else:
    raise SystemExit("No free worktree port in 20000-59999")
PY
    )

    COMPOSE_PROJECT_NAME="autonavlog-wt-${WT_ID}"
    AUTONAVLOG_IMAGE="autonavlog:wt-${WT_ID}"
    AUTONAVLOG_HOST_PORT="$WT_PORT"
    AUTONAVLOG_BIND_ADDRESS="127.0.0.1"
    AUTONAVLOG_TRUSTED_LOCAL_IDENTITY="local-user"
    AUTONAVLOG_SESSION_COOKIE_SECURE="false"

    if grep -qi microsoft /proc/sys/kernel/osrelease 2>/dev/null; then
        COMPOSE_FILE="compose.yaml:compose.wsl.yaml:.autonavlog-worktree/compose.override.yaml"
    else
        COMPOSE_FILE="compose.yaml:.autonavlog-worktree/compose.override.yaml"
    fi

    cat >"$ENV_FILE" <<EOF
${MARKER}
COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
COMPOSE_FILE=${COMPOSE_FILE}
AUTONAVLOG_IMAGE=${AUTONAVLOG_IMAGE}
AUTONAVLOG_HOST_PORT=${AUTONAVLOG_HOST_PORT}
AUTONAVLOG_BIND_ADDRESS=${AUTONAVLOG_BIND_ADDRESS}
AUTONAVLOG_TRUSTED_LOCAL_IDENTITY=${AUTONAVLOG_TRUSTED_LOCAL_IDENTITY}
AUTONAVLOG_SESSION_COOKIE_SECURE=${AUTONAVLOG_SESSION_COOKIE_SECURE}
EOF
fi

if [[ ! "$COMPOSE_PROJECT_NAME" =~ ^autonavlog-wt-[0-9a-f]{8}$ ]]; then
    echo "Generated COMPOSE_PROJECT_NAME is invalid: $COMPOSE_PROJECT_NAME" >&2
    exit 1
fi
if [[ ! "$AUTONAVLOG_IMAGE" =~ ^autonavlog:wt-[0-9a-f]{8}$ ]]; then
    echo "Generated AUTONAVLOG_IMAGE is invalid: $AUTONAVLOG_IMAGE" >&2
    exit 1
fi
if [[ ! "$AUTONAVLOG_HOST_PORT" =~ ^[0-9]+$ ]] || (( AUTONAVLOG_HOST_PORT < 20000 || AUTONAVLOG_HOST_PORT > 59999 )); then
    echo "Generated AUTONAVLOG_HOST_PORT is invalid: $AUTONAVLOG_HOST_PORT" >&2
    exit 1
fi

write_override
npm --prefix web ci

printf 'Codex worktree ready: project=%s port=%s\n' "$COMPOSE_PROJECT_NAME" "$AUTONAVLOG_HOST_PORT"
printf 'NavMate URL after startup: http://127.0.0.1:%s\n' "$AUTONAVLOG_HOST_PORT"
