"""Setup remains usable without host Node and never targets the primary runtime."""

import os
import shutil
import subprocess
import tempfile
import unittest
from pathlib import Path

SCRIPT = Path(__file__).resolve().parents[2] / "scripts/codex/setup_worktree.sh"


class WorktreeSetupTests(unittest.TestCase):
    def run_setup(self, *, host_node=False, cpus="8", existing=True):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            bin_dir = root / "bin"
            bin_dir.mkdir()
            for command in ("bash", "python3", "grep", "mkdir", "cat", "id"):
                (bin_dir / command).symlink_to(shutil.which(command))
            git = bin_dir / "git"
            git.write_text('#!/bin/sh\nprintf "%s\\n" "$PWD"\n')
            git.chmod(0o755)
            log = root / "commands"
            docker = bin_dir / "docker"
            docker.write_text(
                '#!/bin/sh\nprintf "%s\\n" "$*" >> "$TEST_LOG"\n'
                'if [ "$1" = info ]; then printf "%s\\n" "$TEST_CPUS"; fi\n'
            )
            docker.chmod(0o755)
            if host_node:
                for name in ("node", "npm"):
                    path = bin_dir / name
                    path.write_text('#!/bin/sh\nprintf "host %s\\n" "$*" >> "$TEST_LOG"\n')
                    path.chmod(0o755)
            env_file = root / ".env"
            content = (
                (
                    "# Generated by AutoNavLog Codex worktree setup\n"
                    "COMPOSE_PROJECT_NAME=autonavlog-wt-01234567\n"
                    "COMPOSE_FILE=compose.yaml:.autonavlog-worktree/compose.override.yaml\n"
                    "AUTONAVLOG_IMAGE=autonavlog:wt-01234567\n"
                    "AUTONAVLOG_HOST_PORT=24567\n"
                )
                if existing
                else "COMPOSE_PROJECT_NAME=autonavlog\n"
            )
            env_file.write_text(content)
            result = subprocess.run(
                ["bash", str(SCRIPT)],
                cwd=root,
                text=True,
                capture_output=True,
                env={**os.environ, "PATH": str(bin_dir), "TEST_LOG": str(log), "TEST_CPUS": cpus},
            )
            self.assertEqual(env_file.read_text(), content)
            override = root / ".autonavlog-worktree/compose.override.yaml"
            return result, log.read_text(), override.read_text() if override.exists() else ""

    def test_missing_node_uses_owned_docker_install_and_caps_cpu(self):
        result, log, override = self.run_setup()
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn(f"run --rm --user {os.getuid()}:{os.getgid()}", log)
        self.assertIn("node:22-bookworm-slim npm --prefix web ci", log)
        self.assertIn('cpus: "8"', override)
        self.assertIn('image: "autonavlog:wt-01234567"', override)

    def test_host_node_and_large_daemon_keep_existing_limits(self):
        result, log, override = self.run_setup(host_node=True, cpus="16")
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn("host --prefix web ci", log)
        self.assertNotIn("run --rm", log)
        self.assertIn('cpus: "10"', override)

    def test_invalid_cpu_capacity_stops_before_install(self):
        result, log, override = self.run_setup(cpus="0")
        self.assertNotEqual(result.returncode, 0)
        self.assertNotIn("run --rm", log)
        self.assertEqual(override, "")

    def test_user_env_is_never_overwritten(self):
        result, log, override = self.run_setup(existing=False)
        self.assertNotEqual(result.returncode, 0)
        self.assertIn("Refusing to overwrite", result.stderr)
        self.assertNotIn("run --rm", log)
        self.assertEqual(override, "")


if __name__ == "__main__":
    unittest.main()
